name: eslint

on:
  push:
    branches:
      - '*'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Node 16 on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Get NPM cache directory path
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::$(npm cache dir)"

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
